# Generated by Django 4.0.5 on 2022-11-23 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_remove_todo_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='completed',
        ),
    ]
